packages:
  - "packages/*"

allowBuilds:
  esbuild: true
  kuzu: true
  tree-sitter: true
  tree-sitter-c-sharp: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-typescript: true
