packages:
  - "packages/*"

overrides:
  fast-uri: 3.1.4
  postcss: 8.5.18
  tar: ^7.5.16

allowBuilds:
  esbuild: true
  kuzu: true
  tree-sitter: true
  tree-sitter-c-sharp: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-typescript: true
