export const systemId = "system:default";

export const schemaStatements = [
  "CREATE NODE TABLE IF NOT EXISTS System(id STRING, name STRING, summary STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Repo(id STRING, name STRING, path STRING, remoteUrl STRING, branch STRING, commitSha STRING, language STRING, indexedAt STRING, summary STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS File(id STRING, repoId STRING, path STRING, language STRING, hash STRING, loc INT64, batchId STRING, indexedAt STRING, active BOOL, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Code(id STRING, repoId STRING, fileId STRING, kind STRING, name STRING, qualifiedName STRING, startLine INT64, endLine INT64, signature STRING, summary STRING, hash STRING, batchId STRING, indexedAt STRING, active BOOL, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Section(id STRING, repoId STRING, fileId STRING, heading STRING, level INT64, startLine INT64, endLine INT64, text STRING, summary STRING, hash STRING, batchId STRING, indexedAt STRING, active BOOL, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Entity(id STRING, name STRING, kind STRING, description STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Operation(id STRING, verb STRING, entityName STRING, description STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Workflow(id STRING, name STRING, description STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS IndexState(id STRING, repoId STRING, repoName STRING, lastBatchId STRING, lastIndexedAt STRING, lastCommitSha STRING, filesScanned INT64, filesChanged INT64, filesStale INT64, status STRING, error STRING, graphWriteAtomicity STRING, graphWriteStatus STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS GraphWriteBatch(id STRING, batchId STRING, repoIds STRING, repoNames STRING, writerMode STRING, atomicityMode STRING, status STRING, startedAt STRING, updatedAt STRING, completedStage STRING, error STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS RelationFeedback(id STRING, evidenceId STRING, action STRING, reason STRING, createdAt STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS AliasOverride(id STRING, alias STRING, targetRepoId STRING, reason STRING, createdAt STRING, active BOOL, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Contract(id STRING, kind STRING, key STRING, name STRING, description STRING, PRIMARY KEY(id));",
  "CREATE NODE TABLE IF NOT EXISTS Evidence(id STRING, repoId STRING, fileId STRING, filePath STRING, line INT64, raw STRING, rule STRING, confidence DOUBLE, batchId STRING, indexedAt STRING, active BOOL, PRIMARY KEY(id));",
  "CREATE REL TABLE IF NOT EXISTS CONTAINS(FROM System TO Repo, FROM Repo TO File, FROM File TO Code, FROM File TO Section);",
  "CREATE REL TABLE IF NOT EXISTS IMPORTS(FROM File TO File, module STRING, raw STRING, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS CALLS(FROM Code TO Code, confidence DOUBLE, resolution STRING, raw STRING, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS MENTIONS(FROM Code TO Entity, FROM Section TO Entity, confidence DOUBLE);",
  "CREATE REL TABLE IF NOT EXISTS DESCRIBES(FROM Section TO Repo);",
  "CREATE REL TABLE IF NOT EXISTS DOCUMENTS(FROM Section TO Code, confidence DOUBLE);",
  "CREATE REL TABLE IF NOT EXISTS REFERENCES(FROM Section TO File, raw STRING);",
  "CREATE REL TABLE IF NOT EXISTS OPERATES_ON(FROM Code TO Entity, verb STRING, confidence DOUBLE);",
  "CREATE REL TABLE IF NOT EXISTS OWNS_PACKAGE(FROM Repo TO Contract, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS PRODUCES(FROM Repo TO Contract, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS CONSUMES(FROM Repo TO Contract, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS SHARES_CONTRACT(FROM Repo TO Contract, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS CONTRACT_MENTIONS(FROM Contract TO Entity, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS PARTICIPATES_IN(FROM Repo TO Operation, role STRING, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS WORKFLOW_STEP(FROM Workflow TO Operation, step INT64, evidenceId STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS HAS_EVIDENCE(FROM Contract TO Evidence, FROM Repo TO Evidence);",
  "CREATE REL TABLE IF NOT EXISTS USES_PACKAGE(FROM Repo TO Contract, packageName STRING, evidenceId STRING, raw STRING, confidence DOUBLE, batchId STRING, active BOOL);",
  "CREATE REL TABLE IF NOT EXISTS DEPENDS_ON(FROM Repo TO Repo, dependencyType STRING, sourceContractId STRING, targetContractId STRING, evidenceId STRING, raw STRING, confidence DOUBLE, batchId STRING, active BOOL);"
];
